-- Orderly — schéma Supabase (production : uniquement les tables, AUCUNE donnée)
-- À exécuter dans Supabase → SQL Editor → Run.
-- RLS laissé désactivé pour que l'app (clé publishable) lise/écrive ; on le verrouillera avant le lancement réel.

CREATE TABLE IF NOT EXISTS public.users (
  id text PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.channels (
  id text PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.products (
  id text PRIMARY KEY,
  name text NOT NULL,
  price integer NOT NULL DEFAULT 0,
  cost integer NOT NULL DEFAULT 0,
  stock integer NOT NULL DEFAULT 0,
  user_id text,
  channel_id text,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date timestamptz NOT NULL DEFAULT now(),
  customer text NOT NULL,
  phone text NOT NULL,
  product_id text NOT NULL,
  upsell_ids text[] NOT NULL DEFAULT '{}',
  city text NOT NULL DEFAULT '',
  delivery_zone text,
  paid boolean NOT NULL DEFAULT false,
  user_id text,
  channel_id text,
  status text NOT NULL DEFAULT 'new',
  source_key text UNIQUE,
  source_spreadsheet_id text,
  source_row_index integer,
  sale_total integer NOT NULL DEFAULT 0,
  goods_cost_total integer NOT NULL DEFAULT 0,
  closing_fee integer NOT NULL DEFAULT 0,
  delivery_fee integer NOT NULL DEFAULT 0,
  net_after_fees integer NOT NULL DEFAULT 0,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  product_name text NOT NULL DEFAULT '',
  upsell_names text[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS public.app_settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Espaces de travail (pour ouvrir à d'autres demain : 1 space = 1 client/équipe)
CREATE TABLE IF NOT EXISTS public.workspaces (
  id text PRIMARY KEY,
  name text NOT NULL,
  owner_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Colonne pour le suivi client (un client voit seulement SES commandes)
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS client_id text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS client_email text;

-- Membres d'un espace (rôle : owner | member | merchant | client)
CREATE TABLE IF NOT EXISTS public.workspace_members (
  id text PRIMARY KEY,
  workspace_id text NOT NULL,
  email text,
  name text,
  role text NOT NULL DEFAULT 'member',
  merchant_id text,
  invited_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

